apiVersion: v1
kind: Service
metadata:
  name: mftcc-svc
  labels:
    app: mftcc-svc
spec:
  type: NodePort
  ports:
  - name: http-ui-svc
    protocol: TCP
    port: 8443
    targetPort: http-ui
    nodePort: 30191
  selector:
    app: mftcc
    tier: backend
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mftcc-dply
  labels:
    app: mftcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mftcc
  template:
    metadata:
      labels:
        app: mftcc
        tier: backend
    spec:
      containers:
      - name: mftcc
        image: tibco/mftcc:8.0
        ports:
        - name: http-ui
          containerPort: 8443
        env:
          - name: APP_CONFIG_PROFILE
            value: "Docker"
          - name: BW_PROFILE
            value: "Docker"
          - name: CONSUL_SERVER_URL
            value: "http://172.16.22.130:30090"
          - name: BW_LOGLEVEL
            value: "INFO"
        resources:
          requests:
            memory: "1024Mi"