apiVersion: v1
kind: Service
metadata:
  name: mftcc-svc
  labels:
    app: mftcc-svc
spec:
  type: NodePort
  ports:
  - name: http-ui-svc
    protocol: TCP
    port: 8443
    targetPort: http-ui
    nodePort: 30191
  selector:
    app: mftcc
    tier: backend